-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["EVOKER"] = GrimoireStatTargets["EVOKER"] or {}

GrimoireStatTargets["EVOKER"]["augmentation"] = GrimoireStatTargets["EVOKER"]["augmentation"] or {}
GrimoireStatTargets["EVOKER"]["augmentation"]["Mythic+"] = { targets = { crit = 867, haste = 551, mastery = 1310, versatility = 150 } }

GrimoireStatTargets["EVOKER"]["devastation"] = GrimoireStatTargets["EVOKER"]["devastation"] or {}
GrimoireStatTargets["EVOKER"]["devastation"]["Mythic+"] = { targets = { crit = 1130, haste = 687, mastery = 876, versatility = 176 } }

GrimoireStatTargets["EVOKER"]["preservation"] = GrimoireStatTargets["EVOKER"]["preservation"] or {}
GrimoireStatTargets["EVOKER"]["preservation"]["Mythic+"] = { targets = { crit = 943, haste = 881, mastery = 730, versatility = 342 } }
