-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["EVOKER"] = GrimoireStatTargets["EVOKER"] or {}

GrimoireStatTargets["EVOKER"]["augmentation"] = GrimoireStatTargets["EVOKER"]["augmentation"] or {}
GrimoireStatTargets["EVOKER"]["augmentation"]["Mythic+"] = { targets = { crit = 897, haste = 533, mastery = 1344, versatility = 129 } }

GrimoireStatTargets["EVOKER"]["devastation"] = GrimoireStatTargets["EVOKER"]["devastation"] or {}
GrimoireStatTargets["EVOKER"]["devastation"]["Mythic+"] = { targets = { crit = 1104, haste = 729, mastery = 893, versatility = 177 } }

GrimoireStatTargets["EVOKER"]["preservation"] = GrimoireStatTargets["EVOKER"]["preservation"] or {}
GrimoireStatTargets["EVOKER"]["preservation"]["Mythic+"] = { targets = { crit = 933, haste = 913, mastery = 688, versatility = 379 } }
