-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["EVOKER"] = GrimoireStatTargets["EVOKER"] or {}

GrimoireStatTargets["EVOKER"]["augmentation"] = GrimoireStatTargets["EVOKER"]["augmentation"] or {}
GrimoireStatTargets["EVOKER"]["augmentation"]["Mythic+"] = { targets = { crit = 920, haste = 515, mastery = 1468, versatility = 121 } }

GrimoireStatTargets["EVOKER"]["devastation"] = GrimoireStatTargets["EVOKER"]["devastation"] or {}
GrimoireStatTargets["EVOKER"]["devastation"]["Mythic+"] = { targets = { crit = 1149, haste = 754, mastery = 894, versatility = 186 } }

GrimoireStatTargets["EVOKER"]["preservation"] = GrimoireStatTargets["EVOKER"]["preservation"] or {}
GrimoireStatTargets["EVOKER"]["preservation"]["Mythic+"] = { targets = { crit = 909, haste = 952, mastery = 686, versatility = 413 } }
