-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["EVOKER"] = GrimoireStatTargets["EVOKER"] or {}

GrimoireStatTargets["EVOKER"]["augmentation"] = GrimoireStatTargets["EVOKER"]["augmentation"] or {}
GrimoireStatTargets["EVOKER"]["augmentation"]["Raid"] = { targets = { crit = 821, haste = 576, mastery = 808, versatility = 193 }, samples = 1006, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["EVOKER"]["devastation"] = GrimoireStatTargets["EVOKER"]["devastation"] or {}
GrimoireStatTargets["EVOKER"]["devastation"]["Raid"] = { targets = { crit = 945, haste = 684, mastery = 566, versatility = 207 }, samples = 1007, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["EVOKER"]["preservation"] = GrimoireStatTargets["EVOKER"]["preservation"] or {}
GrimoireStatTargets["EVOKER"]["preservation"]["Raid"] = { targets = { crit = 866, haste = 708, mastery = 557, versatility = 207 }, samples = 1008, source = "Warcraft Logs Top 1000 (alle Bosse)" }
