-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["EVOKER"] = GrimoireStatTargets["EVOKER"] or {}

GrimoireStatTargets["EVOKER"]["augmentation"] = GrimoireStatTargets["EVOKER"]["augmentation"] or {}
GrimoireStatTargets["EVOKER"]["augmentation"]["Raid"] = { targets = { crit = 812, haste = 451, mastery = 960, versatility = 32 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["EVOKER"]["devastation"] = GrimoireStatTargets["EVOKER"]["devastation"] or {}
GrimoireStatTargets["EVOKER"]["devastation"]["Raid"] = { targets = { crit = 1072, haste = 575, mastery = 585, versatility = 77 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["EVOKER"]["preservation"] = GrimoireStatTargets["EVOKER"]["preservation"] or {}
GrimoireStatTargets["EVOKER"]["preservation"]["Raid"] = { targets = { crit = 779, haste = 647, mastery = 625, versatility = 82 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
