-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PALADIN"] = GrimoireStatTargets["PALADIN"] or {}

GrimoireStatTargets["PALADIN"]["holy"] = GrimoireStatTargets["PALADIN"]["holy"] or {}
GrimoireStatTargets["PALADIN"]["holy"]["Mythic+"] = { targets = { crit = 718, haste = 1108, mastery = 465, versatility = 669 } }

GrimoireStatTargets["PALADIN"]["protection"] = GrimoireStatTargets["PALADIN"]["protection"] or {}
GrimoireStatTargets["PALADIN"]["protection"]["Mythic+"] = { targets = { crit = 1112, haste = 1046, mastery = 445, versatility = 293 } }

GrimoireStatTargets["PALADIN"]["retribution"] = GrimoireStatTargets["PALADIN"]["retribution"] or {}
GrimoireStatTargets["PALADIN"]["retribution"]["Mythic+"] = { targets = { crit = 1039, haste = 827, mastery = 1032, versatility = 98 } }
