-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PALADIN"] = GrimoireStatTargets["PALADIN"] or {}

GrimoireStatTargets["PALADIN"]["holy"] = GrimoireStatTargets["PALADIN"]["holy"] or {}
GrimoireStatTargets["PALADIN"]["holy"]["Mythic+"] = { targets = { crit = 724, haste = 1047, mastery = 557, versatility = 593 } }

GrimoireStatTargets["PALADIN"]["protection"] = GrimoireStatTargets["PALADIN"]["protection"] or {}
GrimoireStatTargets["PALADIN"]["protection"]["Mythic+"] = { targets = { crit = 1016, haste = 1052, mastery = 457, versatility = 294 } }

GrimoireStatTargets["PALADIN"]["retribution"] = GrimoireStatTargets["PALADIN"]["retribution"] or {}
GrimoireStatTargets["PALADIN"]["retribution"]["Mythic+"] = { targets = { crit = 1035, haste = 797, mastery = 1002, versatility = 102 } }
