-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PALADIN"] = GrimoireStatTargets["PALADIN"] or {}

GrimoireStatTargets["PALADIN"]["holy"] = GrimoireStatTargets["PALADIN"]["holy"] or {}
GrimoireStatTargets["PALADIN"]["holy"]["Mythic+"] = { targets = { crit = 737, haste = 1137, mastery = 421, versatility = 667 } }

GrimoireStatTargets["PALADIN"]["protection"] = GrimoireStatTargets["PALADIN"]["protection"] or {}
GrimoireStatTargets["PALADIN"]["protection"]["Mythic+"] = { targets = { crit = 1088, haste = 1053, mastery = 487, versatility = 276 } }

GrimoireStatTargets["PALADIN"]["retribution"] = GrimoireStatTargets["PALADIN"]["retribution"] or {}
GrimoireStatTargets["PALADIN"]["retribution"]["Mythic+"] = { targets = { crit = 1063, haste = 826, mastery = 1028, versatility = 108 } }
