-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["ROGUE"] = GrimoireStatTargets["ROGUE"] or {}

GrimoireStatTargets["ROGUE"]["assassination"] = GrimoireStatTargets["ROGUE"]["assassination"] or {}
GrimoireStatTargets["ROGUE"]["assassination"]["Mythic+"] = { targets = { crit = 1104, haste = 955, mastery = 597, versatility = 157 } }

GrimoireStatTargets["ROGUE"]["outlaw"] = GrimoireStatTargets["ROGUE"]["outlaw"] or {}
GrimoireStatTargets["ROGUE"]["outlaw"]["Mythic+"] = { targets = { crit = 1188, haste = 924, mastery = 192, versatility = 442 } }

GrimoireStatTargets["ROGUE"]["subtlety"] = GrimoireStatTargets["ROGUE"]["subtlety"] or {}
GrimoireStatTargets["ROGUE"]["subtlety"]["Mythic+"] = { targets = { crit = 558, haste = 734, mastery = 1092, versatility = 407 } }
