-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["ROGUE"] = GrimoireStatTargets["ROGUE"] or {}

GrimoireStatTargets["ROGUE"]["assassination"] = GrimoireStatTargets["ROGUE"]["assassination"] or {}
GrimoireStatTargets["ROGUE"]["assassination"]["Raid"] = { targets = { crit = 1082, haste = 872, mastery = 462, versatility = 32 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["ROGUE"]["outlaw"] = GrimoireStatTargets["ROGUE"]["outlaw"] or {}
GrimoireStatTargets["ROGUE"]["outlaw"]["Raid"] = { targets = { crit = 1124, haste = 874, mastery = 66, versatility = 237 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["ROGUE"]["subtlety"] = GrimoireStatTargets["ROGUE"]["subtlety"] or {}
GrimoireStatTargets["ROGUE"]["subtlety"]["Raid"] = { targets = { crit = 387, haste = 677, mastery = 1037, versatility = 292 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }
