-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["ROGUE"] = GrimoireStatTargets["ROGUE"] or {}

GrimoireStatTargets["ROGUE"]["assassination"] = GrimoireStatTargets["ROGUE"]["assassination"] or {}
GrimoireStatTargets["ROGUE"]["assassination"]["Raid"] = { targets = { crit = 1068, haste = 886, mastery = 453, versatility = 26 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["ROGUE"]["outlaw"] = GrimoireStatTargets["ROGUE"]["outlaw"] or {}
GrimoireStatTargets["ROGUE"]["outlaw"]["Raid"] = { targets = { crit = 1115, haste = 874, mastery = 63, versatility = 242 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["ROGUE"]["subtlety"] = GrimoireStatTargets["ROGUE"]["subtlety"] or {}
GrimoireStatTargets["ROGUE"]["subtlety"]["Raid"] = { targets = { crit = 374, haste = 681, mastery = 1041, versatility = 285 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }
