-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARLOCK"] = GrimoireStatTargets["WARLOCK"] or {}

GrimoireStatTargets["WARLOCK"]["affliction"] = GrimoireStatTargets["WARLOCK"]["affliction"] or {}
GrimoireStatTargets["WARLOCK"]["affliction"]["Mythic+"] = { targets = { crit = 980, haste = 1227, mastery = 485, versatility = 195 } }

GrimoireStatTargets["WARLOCK"]["demonology"] = GrimoireStatTargets["WARLOCK"]["demonology"] or {}
GrimoireStatTargets["WARLOCK"]["demonology"]["Mythic+"] = { targets = { crit = 1066, haste = 927, mastery = 740, versatility = 182 } }

GrimoireStatTargets["WARLOCK"]["destruction"] = GrimoireStatTargets["WARLOCK"]["destruction"] or {}
GrimoireStatTargets["WARLOCK"]["destruction"]["Mythic+"] = { targets = { crit = 954, haste = 969, mastery = 812, versatility = 124 } }
