-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARLOCK"] = GrimoireStatTargets["WARLOCK"] or {}

GrimoireStatTargets["WARLOCK"]["affliction"] = GrimoireStatTargets["WARLOCK"]["affliction"] or {}
GrimoireStatTargets["WARLOCK"]["affliction"]["Raid"] = { targets = { crit = 605, haste = 940, mastery = 591, versatility = 202 }, samples = 100, source = "Warcraft Logs Top 100" }

GrimoireStatTargets["WARLOCK"]["demonology"] = GrimoireStatTargets["WARLOCK"]["demonology"] or {}
GrimoireStatTargets["WARLOCK"]["demonology"]["Raid"] = { targets = { crit = 660, haste = 852, mastery = 617, versatility = 192 }, samples = 100, source = "Warcraft Logs Top 100" }

GrimoireStatTargets["WARLOCK"]["destruction"] = GrimoireStatTargets["WARLOCK"]["destruction"] or {}
GrimoireStatTargets["WARLOCK"]["destruction"]["Raid"] = { targets = { crit = 563, haste = 876, mastery = 731, versatility = 188 }, samples = 100, source = "Warcraft Logs Top 100" }
