-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MONK"] = GrimoireStatTargets["MONK"] or {}

GrimoireStatTargets["MONK"]["brewmaster"] = GrimoireStatTargets["MONK"]["brewmaster"] or {}
GrimoireStatTargets["MONK"]["brewmaster"]["Mythic+"] = { targets = { crit = 1216, haste = 217, mastery = 723, versatility = 798 } }

GrimoireStatTargets["MONK"]["mistweaver"] = GrimoireStatTargets["MONK"]["mistweaver"] or {}
GrimoireStatTargets["MONK"]["mistweaver"]["Mythic+"] = { targets = { crit = 590, haste = 1336, mastery = 737, versatility = 344 } }

GrimoireStatTargets["MONK"]["windwalker"] = GrimoireStatTargets["MONK"]["windwalker"] or {}
GrimoireStatTargets["MONK"]["windwalker"]["Mythic+"] = { targets = { crit = 856, haste = 859, mastery = 1150, versatility = 148 } }
