-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MONK"] = GrimoireStatTargets["MONK"] or {}

GrimoireStatTargets["MONK"]["brewmaster"] = GrimoireStatTargets["MONK"]["brewmaster"] or {}
GrimoireStatTargets["MONK"]["brewmaster"]["Raid"] = { targets = { crit = 946, haste = 324, mastery = 792, versatility = 424 }, samples = 1008, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["MONK"]["mistweaver"] = GrimoireStatTargets["MONK"]["mistweaver"] or {}
GrimoireStatTargets["MONK"]["mistweaver"]["Raid"] = { targets = { crit = 522, haste = 906, mastery = 730, versatility = 237 }, samples = 1008, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["MONK"]["windwalker"] = GrimoireStatTargets["MONK"]["windwalker"] or {}
GrimoireStatTargets["MONK"]["windwalker"]["Raid"] = { targets = { crit = 676, haste = 663, mastery = 960, versatility = 156 }, samples = 1006, source = "Warcraft Logs Top 1000 (alle Bosse)" }
