-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MONK"] = GrimoireStatTargets["MONK"] or {}

GrimoireStatTargets["MONK"]["brewmaster"] = GrimoireStatTargets["MONK"]["brewmaster"] or {}
GrimoireStatTargets["MONK"]["brewmaster"]["Raid"] = { targets = { crit = 1106, haste = 92, mastery = 530, versatility = 596 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MONK"]["mistweaver"] = GrimoireStatTargets["MONK"]["mistweaver"] or {}
GrimoireStatTargets["MONK"]["mistweaver"]["Raid"] = { targets = { crit = 589, haste = 1125, mastery = 416, versatility = 126 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MONK"]["windwalker"] = GrimoireStatTargets["MONK"]["windwalker"] or {}
GrimoireStatTargets["MONK"]["windwalker"]["Raid"] = { targets = { crit = 651, haste = 800, mastery = 954, versatility = 11 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
