-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MONK"] = GrimoireStatTargets["MONK"] or {}

GrimoireStatTargets["MONK"]["brewmaster"] = GrimoireStatTargets["MONK"]["brewmaster"] or {}
GrimoireStatTargets["MONK"]["brewmaster"]["Raid"] = { targets = { crit = 1099, haste = 88, mastery = 509, versatility = 610 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MONK"]["mistweaver"] = GrimoireStatTargets["MONK"]["mistweaver"] or {}
GrimoireStatTargets["MONK"]["mistweaver"]["Raid"] = { targets = { crit = 588, haste = 1107, mastery = 427, versatility = 123 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MONK"]["windwalker"] = GrimoireStatTargets["MONK"]["windwalker"] or {}
GrimoireStatTargets["MONK"]["windwalker"]["Raid"] = { targets = { crit = 647, haste = 774, mastery = 941, versatility = 19 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
