-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARRIOR"] = GrimoireStatTargets["WARRIOR"] or {}

GrimoireStatTargets["WARRIOR"]["arms"] = GrimoireStatTargets["WARRIOR"]["arms"] or {}
GrimoireStatTargets["WARRIOR"]["arms"]["Mythic+"] = { targets = { crit = 1248, haste = 974, mastery = 610, versatility = 123 } }

GrimoireStatTargets["WARRIOR"]["fury"] = GrimoireStatTargets["WARRIOR"]["fury"] or {}
GrimoireStatTargets["WARRIOR"]["fury"]["Mythic+"] = { targets = { crit = 777, haste = 1104, mastery = 1058, versatility = 150 } }

GrimoireStatTargets["WARRIOR"]["protection"] = GrimoireStatTargets["WARRIOR"]["protection"] or {}
GrimoireStatTargets["WARRIOR"]["protection"]["Mythic+"] = { targets = { crit = 893, haste = 1239, mastery = 402, versatility = 368 } }
