-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARRIOR"] = GrimoireStatTargets["WARRIOR"] or {}

GrimoireStatTargets["WARRIOR"]["arms"] = GrimoireStatTargets["WARRIOR"]["arms"] or {}
GrimoireStatTargets["WARRIOR"]["arms"]["Mythic+"] = { targets = { crit = 1234, haste = 966, mastery = 599, versatility = 116 } }

GrimoireStatTargets["WARRIOR"]["fury"] = GrimoireStatTargets["WARRIOR"]["fury"] or {}
GrimoireStatTargets["WARRIOR"]["fury"]["Mythic+"] = { targets = { crit = 741, haste = 1129, mastery = 1044, versatility = 166 } }

GrimoireStatTargets["WARRIOR"]["protection"] = GrimoireStatTargets["WARRIOR"]["protection"] or {}
GrimoireStatTargets["WARRIOR"]["protection"]["Mythic+"] = { targets = { crit = 806, haste = 1266, mastery = 393, versatility = 381 } }
