-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARRIOR"] = GrimoireStatTargets["WARRIOR"] or {}

GrimoireStatTargets["WARRIOR"]["arms"] = GrimoireStatTargets["WARRIOR"]["arms"] or {}
GrimoireStatTargets["WARRIOR"]["arms"]["Raid"] = { targets = { crit = 1159, haste = 907, mastery = 385, versatility = 8 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss" }

GrimoireStatTargets["WARRIOR"]["fury"] = GrimoireStatTargets["WARRIOR"]["fury"] or {}
GrimoireStatTargets["WARRIOR"]["fury"]["Raid"] = { targets = { crit = 578, haste = 949, mastery = 930, versatility = 58 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss" }

GrimoireStatTargets["WARRIOR"]["protection"] = GrimoireStatTargets["WARRIOR"]["protection"] or {}
GrimoireStatTargets["WARRIOR"]["protection"]["Raid"] = { targets = { crit = 771, haste = 986, mastery = 379, versatility = 130 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss" }
