-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["WARRIOR"] = GrimoireStatTargets["WARRIOR"] or {}

GrimoireStatTargets["WARRIOR"]["arms"] = GrimoireStatTargets["WARRIOR"]["arms"] or {}
GrimoireStatTargets["WARRIOR"]["arms"]["Raid"] = { targets = { crit = 1142, haste = 918, mastery = 397, versatility = 8 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["WARRIOR"]["fury"] = GrimoireStatTargets["WARRIOR"]["fury"] or {}
GrimoireStatTargets["WARRIOR"]["fury"]["Raid"] = { targets = { crit = 577, haste = 959, mastery = 929, versatility = 54 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["WARRIOR"]["protection"] = GrimoireStatTargets["WARRIOR"]["protection"] or {}
GrimoireStatTargets["WARRIOR"]["protection"]["Raid"] = { targets = { crit = 769, haste = 983, mastery = 388, versatility = 130 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
