-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MAGE"] = GrimoireStatTargets["MAGE"] or {}

GrimoireStatTargets["MAGE"]["arcane"] = GrimoireStatTargets["MAGE"]["arcane"] or {}
GrimoireStatTargets["MAGE"]["arcane"]["Mythic+"] = { targets = { crit = 759, haste = 1011, mastery = 490, versatility = 683 } }

GrimoireStatTargets["MAGE"]["fire"] = GrimoireStatTargets["MAGE"]["fire"] or {}
GrimoireStatTargets["MAGE"]["fire"]["Mythic+"] = { targets = { crit = 159, haste = 1357, mastery = 952, versatility = 413 } }

GrimoireStatTargets["MAGE"]["frost"] = GrimoireStatTargets["MAGE"]["frost"] or {}
GrimoireStatTargets["MAGE"]["frost"]["Mythic+"] = { targets = { crit = 1059, haste = 660, mastery = 1073, versatility = 143 } }
