-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MAGE"] = GrimoireStatTargets["MAGE"] or {}

GrimoireStatTargets["MAGE"]["arcane"] = GrimoireStatTargets["MAGE"]["arcane"] or {}
GrimoireStatTargets["MAGE"]["arcane"]["Mythic+"] = { targets = { crit = 782, haste = 993, mastery = 490, versatility = 611 } }

GrimoireStatTargets["MAGE"]["fire"] = GrimoireStatTargets["MAGE"]["fire"] or {}
GrimoireStatTargets["MAGE"]["fire"]["Mythic+"] = { targets = { crit = 185, haste = 1312, mastery = 900, versatility = 415 } }

GrimoireStatTargets["MAGE"]["frost"] = GrimoireStatTargets["MAGE"]["frost"] or {}
GrimoireStatTargets["MAGE"]["frost"]["Mythic+"] = { targets = { crit = 1029, haste = 643, mastery = 1059, versatility = 144 } }
