-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MAGE"] = GrimoireStatTargets["MAGE"] or {}

GrimoireStatTargets["MAGE"]["arcane"] = GrimoireStatTargets["MAGE"]["arcane"] or {}
GrimoireStatTargets["MAGE"]["arcane"]["Mythic+"] = { targets = { crit = 766, haste = 1005, mastery = 521, versatility = 688 } }

GrimoireStatTargets["MAGE"]["fire"] = GrimoireStatTargets["MAGE"]["fire"] or {}
GrimoireStatTargets["MAGE"]["fire"]["Mythic+"] = { targets = { crit = 153, haste = 1352, mastery = 942, versatility = 446 } }

GrimoireStatTargets["MAGE"]["frost"] = GrimoireStatTargets["MAGE"]["frost"] or {}
GrimoireStatTargets["MAGE"]["frost"]["Mythic+"] = { targets = { crit = 1030, haste = 659, mastery = 1097, versatility = 187 } }
