-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["MAGE"] = GrimoireStatTargets["MAGE"] or {}

GrimoireStatTargets["MAGE"]["arcane"] = GrimoireStatTargets["MAGE"]["arcane"] or {}
GrimoireStatTargets["MAGE"]["arcane"]["Raid"] = { targets = { crit = 636, haste = 910, mastery = 401, versatility = 376 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MAGE"]["fire"] = GrimoireStatTargets["MAGE"]["fire"] or {}
GrimoireStatTargets["MAGE"]["fire"]["Raid"] = { targets = { crit = 87, haste = 1160, mastery = 755, versatility = 186 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["MAGE"]["frost"] = GrimoireStatTargets["MAGE"]["frost"] or {}
GrimoireStatTargets["MAGE"]["frost"]["Raid"] = { targets = { crit = 927, haste = 536, mastery = 908, versatility = 37 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
