-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PRIEST"] = GrimoireStatTargets["PRIEST"] or {}

GrimoireStatTargets["PRIEST"]["discipline"] = GrimoireStatTargets["PRIEST"]["discipline"] or {}
GrimoireStatTargets["PRIEST"]["discipline"]["Mythic+"] = { targets = { crit = 686, haste = 1315, mastery = 717, versatility = 184 } }

GrimoireStatTargets["PRIEST"]["holy"] = GrimoireStatTargets["PRIEST"]["holy"] or {}
GrimoireStatTargets["PRIEST"]["holy"]["Mythic+"] = { targets = { crit = 949, haste = 915, mastery = 671, versatility = 323 } }

GrimoireStatTargets["PRIEST"]["shadow"] = GrimoireStatTargets["PRIEST"]["shadow"] or {}
GrimoireStatTargets["PRIEST"]["shadow"]["Mythic+"] = { targets = { crit = 762, haste = 936, mastery = 1074, versatility = 107 } }
