-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PRIEST"] = GrimoireStatTargets["PRIEST"] or {}

GrimoireStatTargets["PRIEST"]["discipline"] = GrimoireStatTargets["PRIEST"]["discipline"] or {}
GrimoireStatTargets["PRIEST"]["discipline"]["Mythic+"] = { targets = { crit = 666, haste = 1331, mastery = 728, versatility = 193 } }

GrimoireStatTargets["PRIEST"]["holy"] = GrimoireStatTargets["PRIEST"]["holy"] or {}
GrimoireStatTargets["PRIEST"]["holy"]["Mythic+"] = { targets = { crit = 966, haste = 928, mastery = 681, versatility = 317 } }

GrimoireStatTargets["PRIEST"]["shadow"] = GrimoireStatTargets["PRIEST"]["shadow"] or {}
GrimoireStatTargets["PRIEST"]["shadow"]["Mythic+"] = { targets = { crit = 764, haste = 949, mastery = 1083, versatility = 122 } }
