-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["PRIEST"] = GrimoireStatTargets["PRIEST"] or {}

GrimoireStatTargets["PRIEST"]["discipline"] = GrimoireStatTargets["PRIEST"]["discipline"] or {}
GrimoireStatTargets["PRIEST"]["discipline"]["Raid"] = { targets = { crit = 463, haste = 1458, mastery = 398, versatility = 27 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["PRIEST"]["holy"] = GrimoireStatTargets["PRIEST"]["holy"] or {}
GrimoireStatTargets["PRIEST"]["holy"]["Raid"] = { targets = { crit = 825, haste = 617, mastery = 544, versatility = 137 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["PRIEST"]["shadow"] = GrimoireStatTargets["PRIEST"]["shadow"] or {}
GrimoireStatTargets["PRIEST"]["shadow"]["Raid"] = { targets = { crit = 570, haste = 795, mastery = 1017, versatility = 7 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }
