-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["DRUID"] = GrimoireStatTargets["DRUID"] or {}

GrimoireStatTargets["DRUID"]["balance"] = GrimoireStatTargets["DRUID"]["balance"] or {}
GrimoireStatTargets["DRUID"]["balance"]["Mythic+"] = { targets = { crit = 828, haste = 931, mastery = 1053, versatility = 149 } }

GrimoireStatTargets["DRUID"]["feral"] = GrimoireStatTargets["DRUID"]["feral"] or {}
GrimoireStatTargets["DRUID"]["feral"]["Mythic+"] = { targets = { crit = 838, haste = 840, mastery = 1132, versatility = 175 } }

GrimoireStatTargets["DRUID"]["guardian"] = GrimoireStatTargets["DRUID"]["guardian"] or {}
GrimoireStatTargets["DRUID"]["guardian"]["Mythic+"] = { targets = { crit = 858, haste = 1181, mastery = 455, versatility = 471 } }

GrimoireStatTargets["DRUID"]["restoration"] = GrimoireStatTargets["DRUID"]["restoration"] or {}
GrimoireStatTargets["DRUID"]["restoration"]["Mythic+"] = { targets = { crit = 260, haste = 1424, mastery = 991, versatility = 331 } }
