-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["DRUID"] = GrimoireStatTargets["DRUID"] or {}

GrimoireStatTargets["DRUID"]["balance"] = GrimoireStatTargets["DRUID"]["balance"] or {}
GrimoireStatTargets["DRUID"]["balance"]["Mythic+"] = { targets = { crit = 827, haste = 943, mastery = 1056, versatility = 150 } }

GrimoireStatTargets["DRUID"]["feral"] = GrimoireStatTargets["DRUID"]["feral"] or {}
GrimoireStatTargets["DRUID"]["feral"]["Mythic+"] = { targets = { crit = 839, haste = 844, mastery = 1119, versatility = 179 } }

GrimoireStatTargets["DRUID"]["guardian"] = GrimoireStatTargets["DRUID"]["guardian"] or {}
GrimoireStatTargets["DRUID"]["guardian"]["Mythic+"] = { targets = { crit = 871, haste = 1191, mastery = 453, versatility = 457 } }

GrimoireStatTargets["DRUID"]["restoration"] = GrimoireStatTargets["DRUID"]["restoration"] or {}
GrimoireStatTargets["DRUID"]["restoration"]["Mythic+"] = { targets = { crit = 252, haste = 1423, mastery = 988, versatility = 332 } }
