-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["DRUID"] = GrimoireStatTargets["DRUID"] or {}

GrimoireStatTargets["DRUID"]["balance"] = GrimoireStatTargets["DRUID"]["balance"] or {}
GrimoireStatTargets["DRUID"]["balance"]["Mythic+"] = { targets = { crit = 830, haste = 893, mastery = 1095, versatility = 144 } }

GrimoireStatTargets["DRUID"]["feral"] = GrimoireStatTargets["DRUID"]["feral"] or {}
GrimoireStatTargets["DRUID"]["feral"]["Mythic+"] = { targets = { crit = 844, haste = 834, mastery = 1158, versatility = 179 } }

GrimoireStatTargets["DRUID"]["guardian"] = GrimoireStatTargets["DRUID"]["guardian"] or {}
GrimoireStatTargets["DRUID"]["guardian"]["Mythic+"] = { targets = { crit = 920, haste = 1173, mastery = 478, versatility = 443 } }

GrimoireStatTargets["DRUID"]["restoration"] = GrimoireStatTargets["DRUID"]["restoration"] or {}
GrimoireStatTargets["DRUID"]["restoration"]["Mythic+"] = { targets = { crit = 259, haste = 1429, mastery = 990, versatility = 340 } }
