-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["DRUID"] = GrimoireStatTargets["DRUID"] or {}

GrimoireStatTargets["DRUID"]["balance"] = GrimoireStatTargets["DRUID"]["balance"] or {}
GrimoireStatTargets["DRUID"]["balance"]["Raid"] = { targets = { crit = 614, haste = 758, mastery = 958, versatility = 30 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["DRUID"]["feral"] = GrimoireStatTargets["DRUID"]["feral"] or {}
GrimoireStatTargets["DRUID"]["feral"]["Raid"] = { targets = { crit = 592, haste = 768, mastery = 1102, versatility = 62 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["DRUID"]["guardian"] = GrimoireStatTargets["DRUID"]["guardian"] or {}
GrimoireStatTargets["DRUID"]["guardian"]["Raid"] = { targets = { crit = 537, haste = 1049, mastery = 329, versatility = 341 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["DRUID"]["restoration"] = GrimoireStatTargets["DRUID"]["restoration"] or {}
GrimoireStatTargets["DRUID"]["restoration"]["Raid"] = { targets = { crit = 282, haste = 1001, mastery = 743, versatility = 146 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }
