-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["SHAMAN"] = GrimoireStatTargets["SHAMAN"] or {}

GrimoireStatTargets["SHAMAN"]["elemental"] = GrimoireStatTargets["SHAMAN"]["elemental"] or {}
GrimoireStatTargets["SHAMAN"]["elemental"]["Mythic+"] = { targets = { crit = 957, haste = 710, mastery = 983, versatility = 160 } }

GrimoireStatTargets["SHAMAN"]["enhancement"] = GrimoireStatTargets["SHAMAN"]["enhancement"] or {}
GrimoireStatTargets["SHAMAN"]["enhancement"]["Mythic+"] = { targets = { crit = 729, haste = 899, mastery = 1074, versatility = 100 } }

GrimoireStatTargets["SHAMAN"]["restoration"] = GrimoireStatTargets["SHAMAN"]["restoration"] or {}
GrimoireStatTargets["SHAMAN"]["restoration"]["Mythic+"] = { targets = { crit = 1142, haste = 759, mastery = 236, versatility = 644 } }
