-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["SHAMAN"] = GrimoireStatTargets["SHAMAN"] or {}

GrimoireStatTargets["SHAMAN"]["elemental"] = GrimoireStatTargets["SHAMAN"]["elemental"] or {}
GrimoireStatTargets["SHAMAN"]["elemental"]["Mythic+"] = { targets = { crit = 1029, haste = 727, mastery = 971, versatility = 172 } }

GrimoireStatTargets["SHAMAN"]["enhancement"] = GrimoireStatTargets["SHAMAN"]["enhancement"] or {}
GrimoireStatTargets["SHAMAN"]["enhancement"]["Mythic+"] = { targets = { crit = 752, haste = 932, mastery = 1134, versatility = 107 } }

GrimoireStatTargets["SHAMAN"]["restoration"] = GrimoireStatTargets["SHAMAN"]["restoration"] or {}
GrimoireStatTargets["SHAMAN"]["restoration"]["Mythic+"] = { targets = { crit = 1213, haste = 698, mastery = 293, versatility = 678 } }
