-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["SHAMAN"] = GrimoireStatTargets["SHAMAN"] or {}

GrimoireStatTargets["SHAMAN"]["elemental"] = GrimoireStatTargets["SHAMAN"]["elemental"] or {}
GrimoireStatTargets["SHAMAN"]["elemental"]["Mythic+"] = { targets = { crit = 1014, haste = 758, mastery = 962, versatility = 156 } }

GrimoireStatTargets["SHAMAN"]["enhancement"] = GrimoireStatTargets["SHAMAN"]["enhancement"] or {}
GrimoireStatTargets["SHAMAN"]["enhancement"]["Mythic+"] = { targets = { crit = 754, haste = 933, mastery = 1136, versatility = 87 } }

GrimoireStatTargets["SHAMAN"]["restoration"] = GrimoireStatTargets["SHAMAN"]["restoration"] or {}
GrimoireStatTargets["SHAMAN"]["restoration"]["Mythic+"] = { targets = { crit = 1193, haste = 750, mastery = 267, versatility = 658 } }
