-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["SHAMAN"] = GrimoireStatTargets["SHAMAN"] or {}

GrimoireStatTargets["SHAMAN"]["elemental"] = GrimoireStatTargets["SHAMAN"]["elemental"] or {}
GrimoireStatTargets["SHAMAN"]["elemental"]["Raid"] = { targets = { crit = 806, haste = 701, mastery = 664, versatility = 215 }, samples = 1006, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["SHAMAN"]["enhancement"] = GrimoireStatTargets["SHAMAN"]["enhancement"] or {}
GrimoireStatTargets["SHAMAN"]["enhancement"]["Raid"] = { targets = { crit = 736, haste = 757, mastery = 755, versatility = 129 }, samples = 1008, source = "Warcraft Logs Top 1000 (alle Bosse)" }

GrimoireStatTargets["SHAMAN"]["restoration"] = GrimoireStatTargets["SHAMAN"]["restoration"] or {}
GrimoireStatTargets["SHAMAN"]["restoration"]["Raid"] = { targets = { crit = 904, haste = 691, mastery = 350, versatility = 381 }, samples = 1007, source = "Warcraft Logs Top 1000 (alle Bosse)" }
