-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["HUNTER"] = GrimoireStatTargets["HUNTER"] or {}

GrimoireStatTargets["HUNTER"]["beast-mastery"] = GrimoireStatTargets["HUNTER"]["beast-mastery"] or {}
GrimoireStatTargets["HUNTER"]["beast-mastery"]["Mythic+"] = { targets = { crit = 1307, haste = 283, mastery = 1268, versatility = 227 } }

GrimoireStatTargets["HUNTER"]["marksmanship"] = GrimoireStatTargets["HUNTER"]["marksmanship"] or {}
GrimoireStatTargets["HUNTER"]["marksmanship"]["Mythic+"] = { targets = { crit = 1476, haste = 264, mastery = 1125, versatility = 260 } }

GrimoireStatTargets["HUNTER"]["survival"] = GrimoireStatTargets["HUNTER"]["survival"] or {}
GrimoireStatTargets["HUNTER"]["survival"]["Mythic+"] = { targets = { crit = 873, haste = 798, mastery = 1212, versatility = 105 } }
