-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["HUNTER"] = GrimoireStatTargets["HUNTER"] or {}

GrimoireStatTargets["HUNTER"]["beast-mastery"] = GrimoireStatTargets["HUNTER"]["beast-mastery"] or {}
GrimoireStatTargets["HUNTER"]["beast-mastery"]["Mythic+"] = { targets = { crit = 1251, haste = 324, mastery = 1224, versatility = 231 } }

GrimoireStatTargets["HUNTER"]["marksmanship"] = GrimoireStatTargets["HUNTER"]["marksmanship"] or {}
GrimoireStatTargets["HUNTER"]["marksmanship"]["Mythic+"] = { targets = { crit = 1430, haste = 248, mastery = 1138, versatility = 241 } }

GrimoireStatTargets["HUNTER"]["survival"] = GrimoireStatTargets["HUNTER"]["survival"] or {}
GrimoireStatTargets["HUNTER"]["survival"]["Mythic+"] = { targets = { crit = 914, haste = 771, mastery = 1188, versatility = 77 } }
