-- Generated by scrape_all_murlok.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["HUNTER"] = GrimoireStatTargets["HUNTER"] or {}

GrimoireStatTargets["HUNTER"]["beast-mastery"] = GrimoireStatTargets["HUNTER"]["beast-mastery"] or {}
GrimoireStatTargets["HUNTER"]["beast-mastery"]["Mythic+"] = { targets = { crit = 1296, haste = 263, mastery = 1268, versatility = 263 } }

GrimoireStatTargets["HUNTER"]["marksmanship"] = GrimoireStatTargets["HUNTER"]["marksmanship"] or {}
GrimoireStatTargets["HUNTER"]["marksmanship"]["Mythic+"] = { targets = { crit = 1515, haste = 266, mastery = 1151, versatility = 234 } }

GrimoireStatTargets["HUNTER"]["survival"] = GrimoireStatTargets["HUNTER"]["survival"] or {}
GrimoireStatTargets["HUNTER"]["survival"]["Mythic+"] = { targets = { crit = 901, haste = 829, mastery = 1203, versatility = 97 } }
