-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["HUNTER"] = GrimoireStatTargets["HUNTER"] or {}

GrimoireStatTargets["HUNTER"]["beast-mastery"] = GrimoireStatTargets["HUNTER"]["beast-mastery"] or {}
GrimoireStatTargets["HUNTER"]["beast-mastery"]["Raid"] = { targets = { crit = 895, haste = 534, mastery = 1040, versatility = 28 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["HUNTER"]["marksmanship"] = GrimoireStatTargets["HUNTER"]["marksmanship"] or {}
GrimoireStatTargets["HUNTER"]["marksmanship"]["Raid"] = { targets = { crit = 1436, haste = 164, mastery = 922, versatility = 73 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["HUNTER"]["survival"] = GrimoireStatTargets["HUNTER"]["survival"] or {}
GrimoireStatTargets["HUNTER"]["survival"]["Raid"] = { targets = { crit = 684, haste = 623, mastery = 1141, versatility = 23 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }
