-- Generated by scrape_warcraftlogs_raid.py. Do not edit by hand.
GrimoireStatTargets = GrimoireStatTargets or {}
GrimoireStatTargets["HUNTER"] = GrimoireStatTargets["HUNTER"] or {}

GrimoireStatTargets["HUNTER"]["beast-mastery"] = GrimoireStatTargets["HUNTER"]["beast-mastery"] or {}
GrimoireStatTargets["HUNTER"]["beast-mastery"]["Raid"] = { targets = { crit = 859, haste = 542, mastery = 1026, versatility = 27 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["HUNTER"]["marksmanship"] = GrimoireStatTargets["HUNTER"]["marksmanship"] or {}
GrimoireStatTargets["HUNTER"]["marksmanship"]["Raid"] = { targets = { crit = 1405, haste = 165, mastery = 881, versatility = 90 }, samples = 100, source = "Warcraft Logs Heroisch-Endboss", limited = true }

GrimoireStatTargets["HUNTER"]["survival"] = GrimoireStatTargets["HUNTER"]["survival"] or {}
GrimoireStatTargets["HUNTER"]["survival"]["Raid"] = { targets = { crit = 689, haste = 602, mastery = 1164, versatility = 23 }, samples = 99, source = "Warcraft Logs Heroisch-Endboss", limited = true }
